version: 2
updates:

  # Workflows
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly

  # Mobile Application
  - package-ecosystem: gradle
    directory: /App/
    schedule:
      interval: monthly

  # Server Service
  - package-ecosystem: nuget
    directory: /Service/
    schedule:
      interval: monthly
