name: CI

on:
  push:
    paths:
      - 'App/**'
      - 'Service/**'
      - '.github/workflows/app.yml'
    branches:
      - '**'
    tags:
      - '*.*.*'
  pull_request:
    branches:
    - '**'
  workflow_dispatch:

jobs:
  app:
    name: App
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    defaults:
      run:
        working-directory: ./App/
    strategy:
      matrix:
        variant: [ 'Debug', 'Release' ]
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Set Gradle permissions
        run: chmod +x ./gradlew

      - name: Build project
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assemble${{ matrix.variant }}
          build-root-directory: ./App/

      - name: Run tests
        run: ./gradlew test

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: ServerMonitor-${{ matrix.variant }}
          path: |
            ./App/app/build/outputs/apk/*/*
