name: App

on:
  push:
    paths:
      - 'App/**'
      - '.github/workflows/app.yml'
    branches:
      - '**'
    tags:
      - '*.*.*'
  pull_request:
    branches:
    - '**'
  workflow_dispatch:

env:
  ARTIFACT_NAME: ServerMonitor-App

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./App/
    strategy:
      matrix:
        variant: [ 'Debug', 'Release' ]
    permissions:
      contents: read
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - name: Set Gradle permissions
        run: chmod +x ./gradlew

      - name: Build project
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assemble${{ matrix.variant }} --scan
          build-root-directory: ./App/

      - name: Run instrumented tests
        run: ./gradlew test

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}-${{ matrix.variant }}
          path: |
            ./App/app/build/outputs/apk/*/*
