name: App

on:
  push:
    paths:
      - 'App/**'
      - '.github/workflows/app.yml'
    branches:
      - '**'
    tags:
      - '*.*.*'
  pull_request:
    branches:
    - '**'
  workflow_dispatch:

env:
  ARTIFACT_NAME: ServerMonitor-App

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        variant: [ 'Debug', 'Release' ]
    permissions:
      contents: read
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Set Gradle permissions
        run: chmod +x ./App/gradlew

      - name: Create key store
        id: keystore
        run: |
          echo "${{ secrets.ANDROID_KEY_STORE }}" | base64 -d > $HOME/android-key-store.apk
          echo "path=$HOME/android-key-store.apk" >> "$GITHUB_OUTPUT"

      - name: Build project
        env:
          ANDROID_KEY_STORE_PATH: ${{ steps.keystore.outputs.path }}
          ANDROID_KEY_STORE_PASSWORD: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
          ANDROID_KEY_STORE_KEY_ALIAS: ${{ secrets.ANDROID_KEY_STORE_KEY_ALIAS }}
          ANDROID_KEY_STORE_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_STORE_KEY_PASSWORD }}
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assemble${{ matrix.variant }} --scan
          build-root-directory: ./App/
          cache-disabled: true

      - name: Run instrumented tests
        env:
          ANDROID_KEY_STORE_PATH: ${{ steps.keystore.outputs.path }}
          ANDROID_KEY_STORE_PASSWORD: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
          ANDROID_KEY_STORE_KEY_ALIAS: ${{ secrets.ANDROID_KEY_STORE_KEY_ALIAS }}
          ANDROID_KEY_STORE_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_STORE_KEY_PASSWORD }}
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test --scan
          build-root-directory: ./App/
          cache-disabled: true

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}-${{ matrix.variant }}
          path: |
            ./App/app/build/outputs/apk/*/*
